version: "3"
services:
    db:
        #image: postgres:latest
        build:
            context: .
            dockerfile: Dockerfile
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            #POSTGRES_DB 없으면 유저명으로 생성됨...
            POSTGRES_DB: postgres
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgresql"
            
        volumes:
            - E:/docker/data/postgresql/:/var/lib/postgresql/data
            #- ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
 